# === OAI stage-1: descriptor-only gradients for all classes ===
# Experiment with log barrier loss, while using the config of the best quadratic penalty so..
# both STD & EXP patches, ESP=100, STD patch = [200,200,200], EXP patch=[400,400,400], 600 epochs
#Experiment: centroid-emphasis
# dataset: fixed per-case sampling (1 STD + 1 EXP patch reused for entire training)

# data
images_dir: /ivi/zfs/s0/original_homes/isimion/knee_dataset/OAI_ZIB_DESS
labels_dir: /ivi/zfs/s0/original_homes/isimion/knee_dataset/OAI_ZIB_segmentations
splits_file: /home/isimion/meunet-shape-supervision-oai/nnunet/nnUNet_preprocessed/Dataset701_OAIKnee/splits_final.json
dataset_name: Dataset701_OAIKnee

classes: [0, 1, 2, 3, 4]

# model
in_channels: 1
n_classes: 5
#EXP will become [400,400,400]
patch_size: [200, 200, 200]
expand_factor: 2.0
enc_channels: [16, 32, 64, 128]
dec_channels: [16, 32, 64]
norm: batch

# training / loader
batch_size: 2
num_workers: 8
fg_sampling_prob: 0.5


loss: dice_ce_weighted
smooth_dice_eps: 1.0e-6

optimizer: adam
lr: 0.0009
weight_decay: 1.0e-05
amp: true

epochs: 600
early_stop_patience: 100
min_lr: 1.0e-06
deep_supervision_weight: 0.5

seed: 777
log_every: 25
val_every: 1

#Exp toggles 
use_seg_loss: false         # <— this makes it truly descriptor-only
monitor_seg_loss: true      # <— keeps loss_va_seg + seg(log) comparable
detach_desc_channels_for_seg: true  # irrelevant if use_seg_loss=false, but safe
# all classes
desc_only_classes: [1, 2, 3, 4]
centroid_classes: [1, 2, 3, 4]
volume_classes: [1, 2, 3, 4]
avgdist_classes: [1, 2, 3, 4]
avgdist_axis_classes: [1, 2, 3, 4]
shape_on: both                  # apply shape losses on EXP and STD patches

lambda_volume: 1.0              # small now for first experiment logbarrier
lambda_centroid: 5.0            # small now for first experiment logbarrier
lambda_avgdist: 0.0             # radial mean distance to centroid barrier
lambda_avgdist_axis: 0.0        # per-axis spread-to-centroid barrier
centroid_norm: true             # normalize coords to [0,1]

# #logbarrier toggles
# barrier_t: 5.0
# volume_tolerance: 0.10
# centroid_tolerance: 0.05
# avgdist_tolerance: 0.05
# avgdist_axis_tolerance: 0.05
lambda_moment2: 1.0          # 6 covariance components
lambda_moment3: 0.5          # 10 skewness components
lambda_moment_inv: 0.0       # 3 rotation-invariant scalars (J1/J2/J3)

moment2_tolerance: 0.02
moment3_tolerance: 0.01
moment_inv_tolerance: 0.01


workdir: /home/isimion/meunet-shape-supervision-oai/oai_baselines/meunet_raw/results/stage1_desc_only_all_both_best_logbarrier_centx5_fixedpatch
